export const SET_LOADED_BOOKS_GENRES = "SET_LOADED_BOOKS_GENRES";
export const SET_LOADED_BOOKS_BY_GENRE = "SET_LOADED_BOOKS_BY_GENRE";

export const REGISTRATION_USER_DATA_CHANGED = 'REGISTRATION_USER_DATA_CHANGED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';