export const SET_LOADED_BOOKS_GENRES = "SET_LOADED_BOOKS_GENRES";
export const SET_LOADED_BOOKS_BY_GENRE = "SET_LOADED_BOOKS_BY_GENRE";

export const REGISTRATION_USER_DATA_CHANGED = 'REGISTRATION_USER_DATA_CHANGED';